### ISSUE TITLE
Chrome store link 404?

### ISSUE THREAD

**Issue by yegle** [jdhayford/acid-tabs-extension#11]
It's showing 404 when accessing https://chrome.google.com/webstore/detail/acid-tabs/hgceopemmcmigbmhphbcgkeffommpjfc.

I'm pretty sure it worked previously, but when I try to install the extension on a computer today I can't find it.

**Comment by zooly57** [comment]
Yes, it looks like it was removed from the Chrome web store. Does anyone know why and if it's going to be added back?

**Comment by jdhayford** [comment]
Hey all. Chrome removed the extension about 5 days ago because it requested the `tabs` permissions and supposedly the `tabGroups` permission already gives you access to the `chrome.tabs` API.

I made the changes as soon as it was removed (https://github.com/jdhayford/acid-tabs-extension/commit/d01b5ea0e8dc93e24710c83384758dce51eee8c4) but unfortunately, it is still pending review on the Chrome store. I have sent an additional message to try to expedite the process.

Sorry to anyone for the inconvenience, I hope we can get it back up soon and will drop a comment in here when they finally approve it.

**Comment by jdhayford** [comment]
Chrome responded to the support ticket and has re-approved the extension. It should be back up on the Chrome store and (hopefully) we never have this issue again.

Let me know if anyone has any other questions, if not I will close this issue.

**Comment by ryanbuening** [comment]
I am a first time user. I installed 6.5.2 and am on Chrome 91.0.4472.164. None of my groupings seem to be working. I am also not seeing anything in the extension options page except for the text "SETTINGS PAGE".

![image](https://user-images.githubusercontent.com/812974/126338730-c7323490-8d41-4da1-a534-2f7e9671500d.png)

**Comment by jdhayford** [comment]
@ryanbuening Good catch. It turns out the extension really does need "tabs" permissions after all 🙄 . Not sure why the chrome team told me it didn't. I'm pushing an update to add it back in now.

**Comment by jdhayford** [comment]
The above update is now live, will advise if the Chrome team continues to believe that this extension should not request the "tabs" permission.
