### ISSUE TITLE
Tabs are not grouped in Google Chrome v93.0.4577.82

### ISSUE THREAD

**Issue by haton14** [jdhayford/acid-tabs-extension#23]
![スクリーンショット 2021-09-28 15 27 17](https://user-images.githubusercontent.com/75571105/135034571-8576a0a3-bcc8-4279-a7f3-52be04864392.png)

**Comment by gkindrick** [comment]
I'm experiencing the same issue using Chrome Version 95.0.4638.69 on MacOS 11.6.1. Tabs are no longer joining their assigned groups automatically but _can_ be moved manually. However, when the manually moved tab is selected again, it defaults to its previous behavior (separation and duplicate groups).

An update would be great since I love this plugin so freaking much. @jdhayford please let me know if you need beta testers for a potential fix.

![Screen Shot 2021-11-04 at 10 56 07 AM](https://user-images.githubusercontent.com/903448/140393603-32eacee4-186a-48b5-a7b6-b52e4e281f66.png)

**Comment by tomhollander** [comment]
This is also an issue in Edge 95

**Comment by jackhamburger** [comment]
Does anyone here have a consistent repro process?  Normally, for me my extension works properly for a while and then fails when I have many tabs but there isn't one thing that sticks out.

I setup the dev env for the extension and will be watching logs when this reproduces - if I can reproduce it, I'll fix it.

**Comment by agentgonzo** [comment]
I am seeing this as well. But for me, the tabs still get correctly grouped in the first Chrome window that I have opened. It's only in subsequent Chrome windows that the tabs don't group. I normally get around this by trying to have only one Chrome window open, or treat one as my "primary" chrome window (where I want tabs grouped) and know that all other windows won't have grouping.

There hasn't been any activity on this plugin in 6 months though, so I'll look for another plugin.

**Comment by bsell93** [comment]
@jdhayford I'm seeing this issue as well. I'm also experiencing issues with the tabs not being in the correct order as well. Possibly related. Will try to take a look if I get time

**Comment by agentgonzo** [comment]
It looks like #16 may have fixed this issue. I forked the repo and ran through the instructions in the readme to install it from a locally-built version and it appears to be working for me now from a quick test.

Hopefully all it needs is a release from @jdhayford to the chrome store

**Comment by jdhayford** [comment]
> It looks like #16 may have fixed this issue. I forked the repo and ran through the instructions in the readme to install it from a locally-built version and it appears to be working for me now from a quick test.
> 
> Hopefully all it needs is a release from @jdhayford to the chrome store

Thanks for the comment. I will perform a new release this week 👍🏼

**Comment by haton14** [comment]
@jdhayford 
Thanks for the great release!
